'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be
	1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:

1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
from math import sqrt as sqrt
def makeNthTriangleNum(x):
	return sum([i for i in range(1,x+1)])

def getFactors(x):
	factors = []
	for i in range(1,int(sqrt(x))+1):
		if x%i==0:
			factors.append(i)
			if x != i:
				factors.append(x/i)
	return factors

tri = 28
tri_i = 7
factors = getFactors(28)

while( len(factors) < 500):
	tri_i += 1
	tri += tri_i
	factors = getFactors(tri)

print(tri, tri_i)

#answer: 76576500
